### PR TITLE
CSC Encounter Profiles

### PR DESCRIPTION
**Pull request by wjones46**
I want to upload profiles created by CSC for a list (basic) & details profiles of the encounter resource.

### CODE REVIEW

**Comment by jonnyry** [comment]
Hi Will

I can't see any changed files, or seem to be able to get back to your fork of the repository - is a private repository?  Can you paste a link to forked repository in here?

Thanks
Jonny

**Comment by wjones46** [comment]
I don't think its a private repository.

The only method I have for uploading files is via drag and drop here.  But when I do this the XML file generated from Forge is rejected with the message: "We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.".  ZIP up and upload I guess.  

Also it was mentioned am I going to use a viewer, I assume you mean something like Simplifhir?  I don't currently have access to Simplifhir, is it a free download?

**Comment by wjones46** [comment]
Testing ZIP file upload - please ignore
[CSC Detailed Encounter.structuredefinition v2.zip](https://github.com/HL7-UK/CareConnect-profiles/files/533438/CSC.Detailed.Encounter.structuredefinition.v2.zip)

**Comment by jonnyry** [comment]
Hi Will

Simplifier is available at:  https://www.simplifier.net  and is free to create an account and upload profiles.

Cheers
Jonny

**Comment by jonnyry** [comment]
Will, just re-reading your previous message.  You will need to commit your profiles to the forked branch you created before creating the pull request.  Happy to have a call to explain if you would like.
Cheers
Jonny

**Pull request closed without merging**
